### ISSUE TITLE
panic: crypto/cipher: input not full blocks

### ISSUE THREAD

**Issue by ilaer** [zellyn/kooky#50]
windows 10,go1.16.12,chrome 98.

try to get cookies from ``%UserProfile%\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies``.
return error.
```
panic: crypto/cipher: input not full blocks

goroutine 1 [running]:
crypto/cipher.(*cbcDecrypter).CryptBlocks(0xc00004e190, 0xc0000127c0, 0x3c, 0x3c
, 0xc000012483, 0x3c, 0x3c)
        C:/Go/src/crypto/cipher/cbc.go:119 +0x4e9
github.com/zellyn/kooky/internal/chrome.decryptAESCBC(0xc000012480, 0x3f, 0x3f, 
0xc00000e400, 0x20, 0x20, 0x3eb, 0x0, 0x0, 0x0, ...)
        C:/Users/xxx/go/pkg/mod/github.com/zellyn/kooky@v0.0.0-20210408152652-
87b89e95f98f/internal/chrome/chrome.go:306 +0x20e
github.com/zellyn/kooky/internal/chrome.(*CookieStore).decrypt.func2(0xc00001248
0, 0x3f, 0x3f, 0xc00000e400, 0x20, 0x20, 0x0, 0x0, 0x0, 0xccc060, ...)
        C:/Users/xxx/go/pkg/mod/github.com/zellyn/kooky@v0.0.0-20210408152652-
87b89e95f98f/internal/chrome/chrome.go:223 +0x7d
github.com/zellyn/kooky/internal/chrome.(*CookieStore).decrypt(0xc00010fbc0, 0xc
000012480, 0x3f, 0x3f, 0x0, 0x0, 0x0, 0xc000012480, 0x3f)
        C:/Users/xxx/go/pkg/mod/github.com/zellyn/kooky@v0.0.0-20210408152652-
87b89e95f98f/internal/chrome/chrome.go:261 +0x38b
github.com/zellyn/kooky/internal/chrome.(*CookieStore).ReadCookies.func1(0xc0000
19018, 0xc000142900, 0xc00004e140, 0x6e, 0x6e)
        C:/Users/xxx/go/pkg/mod/github.com/zellyn/kooky@v0.0.0-20210408152652-
87b89e95f98f/internal/chrome/chrome.go:104 +0x506
github.com/zellyn/kooky/internal/utils.VisitTableRows.func1(0xc000019018, 0x13, 
0xc000000700, 0x12, 0x20, 0xc00014a0a4, 0x6e, 0x6e, 0xc000178000, 0x12, ...)    
        C:/Users/xxx/go/pkg/mod/github.com/zellyn/kooky@v0.0.0-20210408152652-
87b89e95f98f/internal/utils/visittablerows.go:25 +0x9c
github.com/go-sqlite/sqlite3.(*btreeTable).visitRecordsInorder.func1(0x0, 0xc000
019018, 0xc00014a090, 0x82, 0x82, 0x0, 0x82, 0x0)
        C:/Users/xxx/go/pkg/mod/github.com/go-sqlite/sqlite3@v0.0.0-2018031310
5335-53dd8e640ee7/btree.go:431 +0x175
github.com/go-sqlite/sqlite3.(*btreeTable).visitRawInorder(0xc00004c300, 0xc0001
0f740, 0xc000172000, 0x1000)
        C:/Users/xxx/go/pkg/mod/github.com/go-sqlite/sqlite3@v0.0.0-2018031310
5335-53dd8e640ee7/btree.go:395 +0x17b
github.com/go-sqlite/sqlite3.(*btreeTable).visitRawInorder(0xc00004c2a0, 0xc0001
0f740, 0x5000000000000, 0x2e08c700f50c92)
        C:/Users/xxx/go/pkg/mod/github.com/go-sqlite/sqlite3@v0.0.0-2018031310
5335-53dd8e640ee7/btree.go:387 +0x2c9
github.com/go-sqlite/sqlite3.(*btreeTable).visitRecordsInorder(0xc00004c2a0, 0xc
00010f8f8, 0xc000167000, 0x1000)
        C:/Users/xxx/go/pkg/mod/github.com/go-sqlite/sqlite3@v0.0.0-2018031310
5335-53dd8e640ee7/btree.go:424 +0x68
github.com/go-sqlite/sqlite3.(*DbFile).VisitTableRecords(0xc00001d2b0, 0xc66b5f,
 0x7, 0xc00010f8f8, 0xc000055730, 0x0)
        C:/Users/xxx/go/pkg/mod/github.com/go-sqlite/sqlite3@v0.0.0-2018031310
5335-53dd8e640ee7/file.go:313 +0x2b8
github.com/zellyn/kooky/internal/utils.VisitTableRows(0xc00001d2b0, 0xc66b5f, 0x
7, 0xc00010f9f0, 0xc00010fa20, 0x0, 0x4c)
        C:/Users/xxx/go/pkg/mod/github.com/zellyn/kooky@v0.0.0-20210408152652-
87b89e95f98f/internal/utils/visittablerows.go:24 +0x266
github.com/zellyn/kooky/internal/chrome.(*CookieStore).ReadCookies(0xc00010fbc0,
 0x0, 0x0, 0x0, 0x9d0f69, 0x2, 0xcc69d8, 0x1, 0x1)
        C:/Users/xxx/go/pkg/mod/github.com/zellyn/kooky@v0.0.0-20210408152652-
87b89e95f98f/internal/chrome/chrome.go:37 +0x245
github.com/zellyn/kooky/chrome.ReadCookies(0xc0000163c0, 0x4c, 0x0, 0x0, 0x0, 0x
0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/xxx/go/pkg/mod/github.com/zellyn/kooky@v0.0.0-20210408152652-
87b89e95f98f/chrome/chrome.go:24 +0x113

```

**Comment by rogerogers** [comment]
latest chrome changed it's cookie file position, can't find local state file by relative path anymore

**Comment by rogerogers** [comment]
#51 i've create a pull request fix this error
